version: "3.9"

services:

  web:
    build: .
    container_name: kml_web
    ports:
      - "54565:5000" # host:container
    environment:
      RATELIMIT_STORAGE_URI: redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379" # host:container
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  worker:
    build: .
    container_name: kml_worker
    command: python app/cleanup_worker.py
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data
    restart: always